---
- name: Sync directory to another path
  hosts: aaptest.progressive.in
  become: yes

  tasks:
    - name: Rsync directory
      ansible.posix.synchronize:
        src: /opt/site24x7/
        dest: /var/lib/awx/logs/
        recursive: yes
        delete: no
